
package com.mycompany.student;

/**
 *
 * @author HP
 */
import java.awt.Color;
import javax.swing.JOptionPane;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.SQLException;
import java.sql.Types;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import javax.swing.table.DefaultTableModel;
import java.util.*;
import java.util.logging.Level;
import java.util.logging.Logger;
import net.proteanit.sql.DbUtils;

public class Supervisorinfo extends javax.swing.JFrame {
    
    
    private static final String username = "user";
    private static final String password = "password";
    private static final String dataConn = "jdbc:mysql://localhost:3306/studentdata?zeroDateTimeBehavior=CONVERT_TO_NULL";
    
    Connection sqlConn = null;
    PreparedStatement pst = null;
    ResultSet rs = null;
    int q,i;

    /**
     * Creates new form 
     */
    
    String usernamee;
    public Supervisorinfo(String username) {
        usernamee = username;
        initComponents();
        populate_table();
        setLocationRelativeTo(null);
    }
    
    private void populate_table(){
        try
        {
         Class.forName("com.mysql.cj.jdbc.Driver");
          sqlConn = DriverManager.getConnection(dataConn,username,password);
          pst = sqlConn.prepareStatement("select * from supervisor");
          
          rs = pst.executeQuery();
          ResultSetMetaData stData = rs.getMetaData();
          
          q = stData.getColumnCount();
          
          DefaultTableModel RecordTable = (DefaultTableModel)jTable1.getModel();
          RecordTable.setRowCount(0);
          
          
          while(rs.next()){
              Vector columnData = new Vector();
              for(i= 1;i<= q ;i++)
              {
               
               columnData.add(rs.getString("supervisor_id"));
               columnData.add(rs.getString("supervisor_name"));
               columnData.add(rs.getString("engineering_branch"));
               columnData.add(rs.getString("position"));
               columnData.add(rs.getDate("leave_start_date"));
               columnData.add(rs.getDate("leave_end_date"));
               
              }
              RecordTable.addRow(columnData);
          }
        }
  catch(ClassNotFoundException | SQLException ex){
      JOptionPane.showMessageDialog(null,ex);
  }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel5 = new javax.swing.JPanel();
        jToggleButton1 = new javax.swing.JToggleButton();
        jToggleButton5 = new javax.swing.JToggleButton();
        jToggleButton4 = new javax.swing.JToggleButton();
        jToggleButton6 = new javax.swing.JToggleButton();
        jToggleButton7 = new javax.swing.JToggleButton();
        jToggleButton8 = new javax.swing.JToggleButton();
        jToggleButton2 = new javax.swing.JToggleButton();
        jLabel7 = new javax.swing.JLabel();
        jToggleButton3 = new javax.swing.JToggleButton();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jTextField4 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jTextID = new javax.swing.JTextField();
        jTextName = new javax.swing.JTextField();
        jComboBox1 = new javax.swing.JComboBox<>();
        jDateChooser2 = new com.toedter.calendar.JDateChooser();
        jDateChooser1 = new com.toedter.calendar.JDateChooser();
        jADD = new javax.swing.JButton();
        jCLEAR = new javax.swing.JButton();
        jDELETE = new javax.swing.JButton();
        jUPDATE = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jComboBox2 = new javax.swing.JComboBox<>();
        jLabel8 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153), 4));
        jPanel1.setToolTipText("");

        jPanel2.setBackground(new java.awt.Color(255, 223, 224));
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153), 3));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "SUPERVISOR ID", " NAME", "BRANCH", "POSITION", "LEAVE START", "LEAVE END"
            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jPanel5.setBackground(new java.awt.Color(255, 204, 204));

        jToggleButton1.setText("COMPUTER");
        jToggleButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton1ActionPerformed(evt);
            }
        });

        jToggleButton5.setText("ELECTRONICS");
        jToggleButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton5ActionPerformed(evt);
            }
        });

        jToggleButton4.setText("EXTC");
        jToggleButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton4ActionPerformed(evt);
            }
        });

        jToggleButton6.setText("MECHANICAL");
        jToggleButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton6ActionPerformed(evt);
            }
        });

        jToggleButton7.setText("CIVIL");
        jToggleButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton7ActionPerformed(evt);
            }
        });

        jToggleButton8.setText("MECHATRONICS");
        jToggleButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton8ActionPerformed(evt);
            }
        });

        jToggleButton2.setText("IT");
        jToggleButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton2ActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        jLabel7.setText("SUPERVISOR DETAILS ACCORDING TO BRANCH");

        jToggleButton3.setText("AIDS");
        jToggleButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton3ActionPerformed(evt);
            }
        });

        jButton1.setText("All Supervisor");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Delete all");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jToggleButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jToggleButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(71, 71, 71)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jToggleButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jToggleButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(54, 54, 54)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jToggleButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jToggleButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 57, Short.MAX_VALUE)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jToggleButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jToggleButton8))
                .addGap(23, 23, 23))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel7)
                .addGap(151, 151, 151))
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(108, 108, 108)
                .addComponent(jButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(103, 103, 103))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jToggleButton1)
                    .addComponent(jToggleButton4)
                    .addComponent(jToggleButton7)
                    .addComponent(jToggleButton3))
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jToggleButton6)
                    .addComponent(jToggleButton2)
                    .addComponent(jToggleButton5)
                    .addComponent(jToggleButton8))
                .addGap(19, 19, 19))
        );

        jButton5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton5.setText("BACK");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton5)
                .addGap(44, 44, 44))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 393, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton5)
                .addContainerGap(12, Short.MAX_VALUE))
        );

        jPanel3.setBackground(new java.awt.Color(204, 255, 255));

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));

        jTextField4.setFont(new java.awt.Font("Segoe UI Black", 1, 18)); // NOI18N
        jTextField4.setText("SUPERVISOR INFORMATION ");
        jTextField4.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jTextField4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField4ActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Sylfaen", 1, 14)); // NOI18N
        jLabel1.setText("SUPERVISOR ID  ");

        jLabel2.setFont(new java.awt.Font("Sylfaen", 1, 14)); // NOI18N
        jLabel2.setText("SUPERVISOR NAME ");

        jLabel3.setFont(new java.awt.Font("Sylfaen", 1, 14)); // NOI18N
        jLabel3.setText("SUPERVISOR BRANCH ");

        jLabel5.setFont(new java.awt.Font("Sylfaen", 1, 14)); // NOI18N
        jLabel5.setText("POSITION");

        jLabel6.setFont(new java.awt.Font("Sylfaen", 1, 14)); // NOI18N
        jLabel6.setText("LEAVE END");

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "comps", "I.T.", "aids", "extc", "electronics", "mech", "civil", "mtrx" }));

        jADD.setText("ADD");
        jADD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jADDActionPerformed(evt);
            }
        });

        jCLEAR.setText("CLEAR ");
        jCLEAR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCLEARActionPerformed(evt);
            }
        });

        jDELETE.setText("DELETE");
        jDELETE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jDELETEActionPerformed(evt);
            }
        });

        jUPDATE.setText("UPDATE");
        jUPDATE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jUPDATEActionPerformed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Sylfaen", 1, 14)); // NOI18N
        jLabel9.setText("LEAVE START ");

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Professor", "Ass.Prof.", "Doctorate", "Junior" }));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jTextID, javax.swing.GroupLayout.DEFAULT_SIZE, 181, Short.MAX_VALUE)
                            .addComponent(jTextName))
                        .addGap(61, 61, 61))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(0, 19, Short.MAX_VALUE)
                        .addComponent(jADD)
                        .addGap(18, 18, 18)
                        .addComponent(jCLEAR)
                        .addGap(34, 34, 34)
                        .addComponent(jDELETE)
                        .addGap(18, 18, 18)
                        .addComponent(jUPDATE)
                        .addGap(38, 38, 38))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addGap(18, 18, 18)
                                .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(jPanel4Layout.createSequentialGroup()
                                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(58, 58, 58)
                                    .addComponent(jDateChooser1, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel4Layout.createSequentialGroup()
                                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jDateChooser2, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel4Layout.createSequentialGroup()
                                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(40, 40, 40)
                                    .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(22, 22, 22)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jTextID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jTextName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel9)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel6))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(54, 54, 54)
                        .addComponent(jDateChooser2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jDateChooser1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(45, 45, 45)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jADD)
                    .addComponent(jCLEAR)
                    .addComponent(jDELETE)
                    .addComponent(jUPDATE))
                .addContainerGap(22, Short.MAX_VALUE))
        );

        jLabel8.setIcon(new javax.swing.ImageIcon("C:\\Users\\91877\\Documents\\NetBeansProjects\\Student\\src\\main\\java\\sup.jpg")); // NOI18N

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(22, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 428, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 268, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(19, 19, 19))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 13, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        dispose();
        Menu1 menu1 = new Menu1(usernamee);
        menu1.setVisible(true);
        
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jToggleButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton1ActionPerformed
        // TODO add your handling code here:
      /* String supervisorid = jTextID.getText();
       String supervisorname = jTextName.getText();
      String branch = (String)jComboBox1.getSelectedItem();
      String post =  (String)jComboBox2.getSelectedItem();
      java.util.Date date1 = jDateChooser2.getDate();
      java.sql.Date sqldate1 = new java.sql.Date(date1.getTime());
      java.util.Date date2 = jDateChooser1.getDate();
      java.sql.Date sqldate2 = new java.sql.Date(date1.getTime());*/
      
     
      
      //String sqlquery = "Select * from supervisor(supervisorID,supervisor_name,supervisorbranch,Post,leavestart,leaveend) where branch = 'COMPUTER'" ;
       {                                        
       try{
           
        Class.forName("com.mysql.cj.jdbc.Driver");
        sqlConn = DriverManager.getConnection(dataConn,username,password);
        String sqlquery = "Select * from supervisor where engineering_branch = 'comps'" ;
     
       pst = sqlConn.prepareStatement(sqlquery);
       ResultSet rs = pst.executeQuery();
        jTable1.setModel(DbUtils.resultSetToTableModel(rs));
            jTable1.setBackground(Color.WHITE);
            jTable1.setOpaque(false);
       
      //pst.executeUpdate();
       JOptionPane.showMessageDialog(this,"Record Displayed");
      
       
           
       }
       catch(ClassNotFoundException | SQLException ex){
           java.util.logging.Logger.getLogger(Supervisorinfo.class.getName()).log(java.util.logging.Level.SEVERE,null,ex);
       }
    }    //populate_table();                                
        
    }//GEN-LAST:event_jToggleButton1ActionPerformed

    private void jToggleButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton2ActionPerformed
        // TODO add your handling code here:
        try{
           
        Class.forName("com.mysql.cj.jdbc.Driver");
        sqlConn = DriverManager.getConnection(dataConn,username,password);
        String sqlquery = "Select * from supervisor where engineering_branch = 'I.T.'" ;
     
       pst = sqlConn.prepareStatement(sqlquery);
       ResultSet rs = pst.executeQuery();
        jTable1.setModel(DbUtils.resultSetToTableModel(rs));
            jTable1.setBackground(Color.WHITE);
            jTable1.setOpaque(false);
       
      //pst.executeUpdate();
       JOptionPane.showMessageDialog(this,"Record Displayed");
      
       
           
       }
       catch(ClassNotFoundException | SQLException ex){
           java.util.logging.Logger.getLogger(Supervisorinfo.class.getName()).log(java.util.logging.Level.SEVERE,null,ex);
       }
        
    }//GEN-LAST:event_jToggleButton2ActionPerformed

    private void jToggleButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton4ActionPerformed
        // TODO add your handling code here:
        try{
           
        Class.forName("com.mysql.cj.jdbc.Driver");
        sqlConn = DriverManager.getConnection(dataConn,username,password);
        String sqlquery = "Select * from supervisor where engineering_branch = 'extc'" ;
     
       pst = sqlConn.prepareStatement(sqlquery);
       ResultSet rs = pst.executeQuery();
        jTable1.setModel(DbUtils.resultSetToTableModel(rs));
            jTable1.setBackground(Color.WHITE);
            jTable1.setOpaque(false);
       
      //pst.executeUpdate();
       JOptionPane.showMessageDialog(this,"Record Displayed");
      
       
           
       }
       catch(ClassNotFoundException | SQLException ex){
           java.util.logging.Logger.getLogger(Supervisorinfo.class.getName()).log(java.util.logging.Level.SEVERE,null,ex);
       }
    }//GEN-LAST:event_jToggleButton4ActionPerformed

    private void jToggleButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton5ActionPerformed
        // TODO add your handling code here:
        try{
           
        Class.forName("com.mysql.cj.jdbc.Driver");
        sqlConn = DriverManager.getConnection(dataConn,username,password);
        String sqlquery = "Select * from supervisor where engineering_branch = 'electronics'" ;
     
       pst = sqlConn.prepareStatement(sqlquery);
       ResultSet rs = pst.executeQuery();
        jTable1.setModel(DbUtils.resultSetToTableModel(rs));
            jTable1.setBackground(Color.WHITE);
            jTable1.setOpaque(false);
       
      //pst.executeUpdate();
       JOptionPane.showMessageDialog(this,"Record Displayed");
      
       
           
       }
       catch(ClassNotFoundException | SQLException ex){
           java.util.logging.Logger.getLogger(Supervisorinfo.class.getName()).log(java.util.logging.Level.SEVERE,null,ex);
       }
    }//GEN-LAST:event_jToggleButton5ActionPerformed

    private void jToggleButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton6ActionPerformed
        // TODO add your handling code here:
        try{
           
        Class.forName("com.mysql.cj.jdbc.Driver");
        sqlConn = DriverManager.getConnection(dataConn,username,password);
        String sqlquery = "Select * from supervisor where engineering_branch = 'mech'" ;
     
       pst = sqlConn.prepareStatement(sqlquery);
       ResultSet rs = pst.executeQuery();
        jTable1.setModel(DbUtils.resultSetToTableModel(rs));
            jTable1.setBackground(Color.WHITE);
            jTable1.setOpaque(false);
       
      //pst.executeUpdate();
       JOptionPane.showMessageDialog(this,"Record Displayed");
      
       
           
       }
       catch(ClassNotFoundException | SQLException ex){
           java.util.logging.Logger.getLogger(Supervisorinfo.class.getName()).log(java.util.logging.Level.SEVERE,null,ex);
       }
    }//GEN-LAST:event_jToggleButton6ActionPerformed
   

    private void jToggleButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton7ActionPerformed
        // TODO add your handling code here:
        try{
           
        Class.forName("com.mysql.cj.jdbc.Driver");
        sqlConn = DriverManager.getConnection(dataConn,username,password);
        String sqlquery = "Select * from supervisor where engineering_branch = 'civil'" ;
     
       pst = sqlConn.prepareStatement(sqlquery);
       ResultSet rs = pst.executeQuery();
        jTable1.setModel(DbUtils.resultSetToTableModel(rs));
            jTable1.setBackground(Color.WHITE);
            jTable1.setOpaque(false);
       
      //pst.executeUpdate();
       JOptionPane.showMessageDialog(this,"Record Displayed");
      
       
           
       }
       catch(ClassNotFoundException | SQLException ex){
           java.util.logging.Logger.getLogger(Supervisorinfo.class.getName()).log(java.util.logging.Level.SEVERE,null,ex);
       }
    }//GEN-LAST:event_jToggleButton7ActionPerformed

    private void jToggleButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton8ActionPerformed
        // TODO add your handling code here:
        try{
           
        Class.forName("com.mysql.cj.jdbc.Driver");
        sqlConn = DriverManager.getConnection(dataConn,username,password);
        String sqlquery = "Select * from supervisor where engineering_branch = 'mtrx'" ;
     
       pst = sqlConn.prepareStatement(sqlquery);
       ResultSet rs = pst.executeQuery();
        jTable1.setModel(DbUtils.resultSetToTableModel(rs));
            jTable1.setBackground(Color.WHITE);
            jTable1.setOpaque(false);
       
      //pst.executeUpdate();
       JOptionPane.showMessageDialog(this,"Record Displayed");
      
       
           
       }
       catch(ClassNotFoundException | SQLException ex){
           java.util.logging.Logger.getLogger(Supervisorinfo.class.getName()).log(java.util.logging.Level.SEVERE,null,ex);
       }
    }//GEN-LAST:event_jToggleButton8ActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        // TODO add your handling code here:
//     String supervisorid = jTextID.getText();
//      String supervisorname = jTextName.getText();
//      String branch = (String)jComboBox1.getSelectedItem();
//   String position =  (String)jComboBox2.getSelectedItem();
//      java.util.Date date1 = jDateChooser2.getDate();
//      java.sql.Date sqldate1 = new java.sql.Date(date1.getTime());
//      java.util.Date date2 = jDateChooser1.getDate();
//      java.sql.Date sqldate2 = new java.sql.Date(date1.getTime());
//        
//         
//       DefaultTableModel RecordTable = (DefaultTableModel)jTable1.getModel();
//       int selectedRows = jTable1.getSelectedRow();
//       jTextID.setText(RecordTable.getValueAt(selectedRows,0).toString());
//       jTextName.setText(RecordTable.getValueAt(selectedRows,1).toString());
//       
//       String branch1= RecordTable.getValueAt(selectedRows,2).toString();
//       switch(branch1){
//           case "COMPUTER":
//           jComboBox1.setSelectedItem(0);
//           break;
//           
//           case "IT":
//           jComboBox1.setSelectedItem(1);
//           break;
//           
//           case "AIDS":
//           jComboBox1.setSelectedItem(2);
//           break;
//           
//           case "EXTC":
//           jComboBox1.setSelectedItem(3);
//           break;
//           
//           case "ELECTRONICS":
//           jComboBox1.setSelectedItem(4);
//           break;
//           
//           case "MECHANICAL":
//           jComboBox1.setSelectedItem(5);
//           break;
//           
//           case "CIVIL":
//           jComboBox1.setSelectedItem(6);
//           break;
//           
//           case "MECHATRONICS":
//           jComboBox1.setSelectedItem(7);
//           break;
//           
//           
//           
//         }
//       
//        try {
//                  String post1= RecordTable.getValueAt(selectedRows,3).toString();
//       switch(post1){
//           case "Professor":
//          jComboBox2.setSelectedItem(0);
//           break;
//           
//           case "Ass.Prof.":
//           jComboBox2.setSelectedItem(1);
//           break;
//           
//           case "Doctorate":
//           jComboBox2.setSelectedItem(2);
//           break;
//           
//         case "Junior":
//           jComboBox2.setSelectedItem(3);
//           break;
//
//           
//       }
//Date date = new SimpleDateFormat("yyyy-MM-dd").parse((String)RecordTable.getValueAt(selectedRows,4));
//        } catch (ParseException ex) {
//            Logger.getLogger(Supervisorinfo.class.getName()).log(Level.SEVERE, null, ex);
//        }
//       jDateChooser2.setDate(date1);
//       
//       jDateChooser1.setDate(date2);

int r = jTable1.getSelectedRow();
       String tableclicked = jTable1.getModel().getValueAt(r,0).toString();
      
       String sqlquery = "Select * from supervisor WHERE supervisor_id='"+tableclicked+"'";
       /*jTextID.setText(RecordTable.getValueAt(selectedRows,1).toString());
       jTextName.setText(RecordTable.getValueAt(selectedRows,2).toString());*/
       try{
        Class.forName("com.mysql.cj.jdbc.Driver");
        sqlConn = DriverManager.getConnection(dataConn,username,password);
       
       pst = sqlConn.prepareStatement(sqlquery);   
       ResultSet rs = pst.executeQuery();
       if(rs.next())
       {
         String supervisorid = rs.getString(1);
        String supervisorname = rs.getString(2);
        String branch = rs.getString(3);
        String position = rs.getString(4);
        java.sql.Date sqldate1 = rs.getDate(5);
        java.sql.Date sqldate2 = rs.getDate(6);
       
       jTextID.setText(supervisorid);
       jTextName.setText(supervisorname);
       jComboBox1.setSelectedItem(branch);
       jComboBox2.setSelectedItem(position);
      jDateChooser2.setDate(sqldate1);
      jDateChooser1.setDate(sqldate2);
     
       }
       }
      catch(Exception e){
      e.printStackTrace();
 
      }
    
  
    }//GEN-LAST:event_jTable1MouseClicked

    private void jToggleButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton3ActionPerformed
        // TODO add your handling code here:
        //aids branch
        try{
           
        Class.forName("com.mysql.cj.jdbc.Driver");
        sqlConn = DriverManager.getConnection(dataConn,username,password);
        String sqlquery = "Select * from supervisor where engineering_branch = 'aids'" ;
     
       pst = sqlConn.prepareStatement(sqlquery);
       ResultSet rs = pst.executeQuery();
        jTable1.setModel(DbUtils.resultSetToTableModel(rs));
            jTable1.setBackground(Color.WHITE);
            jTable1.setOpaque(false);
       
      //pst.executeUpdate();
       JOptionPane.showMessageDialog(this,"Record Displayed");
      
       
           
       }
       catch(ClassNotFoundException | SQLException ex){
           java.util.logging.Logger.getLogger(Supervisorinfo.class.getName()).log(java.util.logging.Level.SEVERE,null,ex);
       }
                                
    }//GEN-LAST:event_jToggleButton3ActionPerformed

    private void jUPDATEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jUPDATEActionPerformed
  


//String supervisorid = jTextID.getText();
//String supervisorname = jTextName.getText();
//String branch = (String) jComboBox1.getSelectedItem();
//String position = (String) jComboBox2.getSelectedItem();
//java.util.Date date1 = jDateChooser2.getDate();
//java.sql.Date sqldate1 = new java.sql.Date(date1.getTime());
//java.util.Date date2 = jDateChooser1.getDate();
//java.sql.Date sqldate2 = new java.sql.Date(date2.getTime());
//
//try {
//    Class.forName("com.mysql.cj.jdbc.Driver");
//    sqlConn = DriverManager.getConnection(dataConn, username, password);
//
//    int r = jTable1.getSelectedRow();
//    String tableclicked = jTable1.getModel().getValueAt(r, 0).toString();
//    String sqlquery = "UPDATE supervisor SET supervisor_name=?, engineering_branch=?, position=?, leave_start_date=?, leave_end_date=? WHERE supervisor_id = ?";
//    pst = sqlConn.prepareStatement(sqlquery);
//    pst.setString(1, supervisorname);
//    pst.setString(2, branch);
//    pst.setString(3, position);
//    pst.setDate(4, sqldate1);
//    pst.setDate(5, sqldate2);
//    pst.setString(6, tableclicked); // Set the value for the placeholder
//
//    int rowsUpdated = pst.executeUpdate();
//
//    if (rowsUpdated > 0) {
//        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
//        model.setRowCount(0);
//        populate_table();
//        JOptionPane.showMessageDialog(null, "Updated Successfully");
//    } else {
//        JOptionPane.showMessageDialog(null, "Update failed. No rows were updated.");
//    }
//
//    pst.close();
//    sqlConn.close();
//} catch (ClassNotFoundException | SQLException ex) {
//    java.util.logging.Logger.getLogger(Supervisorinfo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//}

String supervisorid = jTextID.getText();
String supervisorname = jTextName.getText();
String branch = (String) jComboBox1.getSelectedItem();
String position = (String) jComboBox2.getSelectedItem();
java.util.Date date1 = jDateChooser2.getDate();
java.sql.Date sqldate1 = null; // Initialize to null

if (date1 != null) {
    sqldate1 = new java.sql.Date(date1.getTime());
}

java.util.Date date2 = jDateChooser1.getDate();
java.sql.Date sqldate2 = null; // Initialize to null

if (date2 != null) {
    sqldate2 = new java.sql.Date(date2.getTime());
}

try {
    Class.forName("com.mysql.cj.jdbc.Driver");
    sqlConn = DriverManager.getConnection(dataConn, username, password);

    int r = jTable1.getSelectedRow();
    String tableclicked = jTable1.getModel().getValueAt(r, 0).toString();
    String sqlquery = "UPDATE supervisor SET supervisor_name=?, engineering_branch=?, position=?, leave_start_date=?, leave_end_date=? WHERE supervisor_id = ?";
    pst = sqlConn.prepareStatement(sqlquery);
    pst.setString(1, supervisorname);
    pst.setString(2, branch);
    pst.setString(3, position);

    if (sqldate1 != null) {
        pst.setDate(4, sqldate1);
    } else {
        pst.setNull(4, Types.DATE); // Set the parameter to NULL
    }

    if (sqldate2 != null) {
        pst.setDate(5, sqldate2);
    } else {
        pst.setNull(5, Types.DATE); // Set the parameter to NULL
    }

    pst.setString(6, tableclicked);

    int rowsUpdated = pst.executeUpdate();

    if (rowsUpdated > 0) {
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        model.setRowCount(0);
        populate_table();
        JOptionPane.showMessageDialog(null, "Updated Successfully");
    } else {
        JOptionPane.showMessageDialog(null, "Update failed. No rows were updated.");
    }

    pst.close();
    sqlConn.close();
} catch (ClassNotFoundException | SQLException ex) {
    java.util.logging.Logger.getLogger(Supervisorinfo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
}



    }//GEN-LAST:event_jUPDATEActionPerformed

    private void jDELETEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jDELETEActionPerformed
        // TODO add your handling code here:
        try{
            Class.forName("com.mysql.cj.jdbc.Driver");
            sqlConn = DriverManager.getConnection(dataConn,username,password);

            int r = jTable1.getSelectedRow();
            String value = jTable1.getModel().getValueAt(r,0).toString();
            String sqlquery = "DELETE FROM supervisor WHERE supervisor_id="+value;
            pst = sqlConn.prepareStatement(sqlquery);
            pst.executeUpdate();
            DefaultTableModel model = (DefaultTableModel)jTable1.getModel();
            model.setRowCount(0);
            populate_table();
            JOptionPane.showMessageDialog(null,"Deleted Successfully");

        }  catch(ClassNotFoundException | SQLException ex){
            java.util.logging.Logger.getLogger(Supervisorinfo.class.getName()).log(java.util.logging.Level.SEVERE,null,ex);
        }

    }//GEN-LAST:event_jDELETEActionPerformed

    private void jCLEARActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCLEARActionPerformed
        // TODO add your handling code here:
        jTextID.setText("");
        jTextName.setText("");
        jComboBox1.setSelectedItem(-1);
        jComboBox2.setSelectedItem(-1);
        jDateChooser1.setDate(null);
        jDateChooser2.setDate(null);

    }//GEN-LAST:event_jCLEARActionPerformed

    private void jADDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jADDActionPerformed
    String supervisorid = jTextID.getText();
    String supervisorname = jTextName.getText();
    String branch = (String) jComboBox1.getSelectedItem();
    String position = (String) jComboBox2.getSelectedItem();
    java.util.Date date1 = jDateChooser2.getDate();
    java.util.Date date2 = jDateChooser1.getDate();

    java.sql.Date sqldate1 = null;
    if (date1 != null) {
        sqldate1 = new java.sql.Date(date1.getTime());
    }

    java.sql.Date sqldate2 = null;
    if (date2 != null) {
        sqldate2 = new java.sql.Date(date2.getTime());
    }

    String sqlquery = "INSERT INTO supervisor (supervisor_id, supervisor_name, engineering_branch, position, leave_start_date, leave_end_date) VALUES (?, ?, ?, ?, ?, ?)";
    
    try {
        Class.forName("com.mysql.cj.jdbc.Driver");
        sqlConn = DriverManager.getConnection(dataConn, username, password);
        pst = sqlConn.prepareStatement(sqlquery);

        pst.setString(1, supervisorid);
        pst.setString(2, supervisorname);
        pst.setString(3, branch);
        pst.setString(4, position);
        
        if (sqldate1 != null) {
            pst.setDate(5, sqldate1);
        } else {
            pst.setNull(5, java.sql.Types.DATE);
        }
        
        if (sqldate2 != null) {
            pst.setDate(6, sqldate2);
        } else {
            pst.setNull(6, java.sql.Types.DATE);
        }

        pst.executeUpdate();
        JOptionPane.showMessageDialog(this, "Record Added");

    } catch (ClassNotFoundException | SQLException ex) {
        java.util.logging.Logger.getLogger(Supervisorinfo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } finally {
        if (pst != null) {
            try {
                pst.close();
            } catch (SQLException e) {
                // Handle any potential SQLException from closing the statement
            }
        }
        if (sqlConn != null) {
            try {
                sqlConn.close();
            } catch (SQLException e) {
                // Handle any potential SQLException from closing the connection
            }
        }
    }

    populate_table();
        
    }//GEN-LAST:event_jADDActionPerformed
 
    private void jTextField4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField4ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        
        try{
           
        Class.forName("com.mysql.cj.jdbc.Driver");
        sqlConn = DriverManager.getConnection(dataConn,username,password);
        String sqlquery = "Select * from supervisor" ;
     
       pst = sqlConn.prepareStatement(sqlquery);
       ResultSet rs = pst.executeQuery();
        jTable1.setModel(DbUtils.resultSetToTableModel(rs));
            jTable1.setBackground(Color.WHITE);
            jTable1.setOpaque(false);
       
      //pst.executeUpdate();
       JOptionPane.showMessageDialog(this,"Record Displayed");
      
       
           
       }
       catch(ClassNotFoundException | SQLException ex){
           java.util.logging.Logger.getLogger(Supervisorinfo.class.getName()).log(java.util.logging.Level.SEVERE,null,ex);
       }
        
    
    
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(null,"All Sample data will get erase so no delete operation but we can delete all");
    }//GEN-LAST:event_jButton2ActionPerformed
/**
     * @param args the command line arguments
     */  

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Supervisorinfo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Supervisorinfo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Supervisorinfo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Supervisorinfo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Supervisorinfo("jain").setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jADD;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jCLEAR;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JButton jDELETE;
    private com.toedter.calendar.JDateChooser jDateChooser1;
    private com.toedter.calendar.JDateChooser jDateChooser2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextID;
    private javax.swing.JTextField jTextName;
    private javax.swing.JToggleButton jToggleButton1;
    private javax.swing.JToggleButton jToggleButton2;
    private javax.swing.JToggleButton jToggleButton3;
    private javax.swing.JToggleButton jToggleButton4;
    private javax.swing.JToggleButton jToggleButton5;
    private javax.swing.JToggleButton jToggleButton6;
    private javax.swing.JToggleButton jToggleButton7;
    private javax.swing.JToggleButton jToggleButton8;
    private javax.swing.JButton jUPDATE;
    // End of variables declaration//GEN-END:variables
}
